server:
  port: 11020

spring:
  profiles:
    group:
      local: "LOG_CONSOLE,LOG_FILE"
      dev: "LOG_CONSOLE,LOG_FILE"
      prd: "LOG_FILE"
    #active: local
    active: dev
  application:
    name: keycloak-role-service

management:
  server:
    port: 11021
  endpoints:
    web:
      base-path: /

keycloak:
  realm: PNMS
  bearer-only: true
  # auth-server-url: http://192.168.101.188:8389
  #auth-server-url: https://dev.pnms.t-sdn.com:9360/ga
  auth-server-url: http://192.168.106.25:30715
  ssl-required: external
  #resource: pnmsrestfulapp
  #resource: web-localhost
  resource: test-jy
  credentials:
    #secret: AJss8oldszgsKccB0uFcqg90WiIlbNfY
    #secret: MPlSC9FJYc9rHexlpScZJZu07IHuqxs2
   #secret: C0Zyh2KiSmJmR3H4PXQmKiSF8N3Wlm1g
   #secret : 2iHxntBSfi3xZ86vtawZS8DkcNZGaywX
   secret : be08l2wrAexqVeOHouNPsYJ8rL6WoV3B
  confidential-port: 0

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    oauth:
      #clientId: web-localhost
      clientId: ${keycloak.resource}
      clientSecret: ${keycloak.credentials.secret}
    oauth2-redirect-url: http://localhost:${server.port}
  oAuthFlow:
    authorizationUrl: ${keycloak.auth-server-url}/realms/PNMS/protocol/openid-connect/auth
    tokenUrl: ${keycloak.auth-server-url}/realms/PNMS/protocol/openid-connect/token

---
spring:
  config:
    activate:
      on-profile: local
    import: "application-local.yml"

---
spring:
  config:
    activate:
      on-profile: dev
    import: "application-dev.yml"